name: Conventional Commits

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate commit messages
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
